### ISSUE TITLE
Embedding fonts in epub? 

### ISSUE THREAD

**Issue by stateanomaly** [davorg/make-ebook#5]
Is there a way to embed fonts in the epub? I tried adding the following to metadata.xml, but it doesn't work. 

`<item id="epub.embedded.font" href="Bookerly-Regular.ttf" media-type="font/truetype"/>`

**Comment by davorg** [comment]
Yes. Pandoc has support for embedding fonts. See the --epub-embed-font option at http://pandoc.org/MANUAL.html

**Comment by stateanomaly** [comment]
Thank you!
